First_MVC_APP/Controllers/DepartmentController.cs
using AutoMapper;
using First_MVC_App.PLL.Interfaces;
using First_MVC_APP.DAL.Data.Models;
using First_MVC_APP.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace First_MVC_APP.PL.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public DepartmentController(IMapper mapper,IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
            
        }

        // main page
        public IActionResult Index()
        {
            var departments = _unitOfWork.DepartmentRepository.GetAll();
            var MappedDept = _mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(departments);
            return View(MappedDept);
        }

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DepartmentViewModel departmentVM)
        {
            if (ModelState.IsValid)
            {
                var mappedDept = _mapper.Map<DepartmentViewModel, Department>(departmentVM);
                _unitOfWork.DepartmentRepository.Add(mappedDept);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(departmentVM);
            }
        }
        #endregion

        #region Details
        public IActionResult Details(int? id, String viewName = "Details")
        {
            if (!id.HasValue)
                return BadRequest();
            var department = _unitOfWork.DepartmentRepository.GetById(id.Value);
            _unitOfWork.Complete();

            if (department is null)
                return NotFound();
            var mappedDept = _mapper.Map<Department, DepartmentViewModel>(department);

            return View(viewName, mappedDept);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int? id)
        {
            return Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute] int id, DepartmentViewModel departmentVM)
        {
            if (id != departmentVM.Id || departmentVM is null)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var mappedDept = _mapper.Map<DepartmentViewModel, Department>(departmentVM);
                    _unitOfWork.DepartmentRepository.Update(mappedDept);
                    _unitOfWork.Complete();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(String.Empty, ex.Message);
                }
            }
            return View(departmentVM);

        }
        #endregion

        #region Delete
        public IActionResult Delete(int? id)
        {
            return Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([FromRoute] int id, DepartmentViewModel departmentVM)
        {
            if (id != departmentVM.Id || departmentVM is null)
                return BadRequest();

                try
                {
                var mappedDept = _mapper.Map<DepartmentViewModel, Department>(departmentVM);
                _unitOfWork.DepartmentRepository.Delete(mappedDept);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(String.Empty, ex.Message);
                }
            
            return View(departmentVM);
        } 
        #endregion
    }
}

First_MVC_APP/Controllers/EmployeeController.cs
using AutoMapper;
using First_MVC_App.PLL.Interfaces;
using First_MVC_APP.DAL.Data.Models;
using First_MVC_APP.PL.Hellpers;
using First_MVC_APP.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace First_MVC_APP.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public EmployeeController(IMapper mapper ,IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }

        // main page
        public IActionResult Index(String searchInput)
        {
            var employees = Enumerable.Empty<Employee>();
            if (String.IsNullOrEmpty(searchInput))
                 employees = _unitOfWork.EmployeeRepository.GetAll();

            else
                employees = _unitOfWork.EmployeeRepository.SearchByName(searchInput);

            var MappedEmp = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel> >(employees);
            return View(MappedEmp);
        }

        #region Create
      
        public IActionResult Create()
        {
      
            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeeViewModel employeeVM)
        {

            if (ModelState.IsValid)
            {
                employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "images");

                var employee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                _unitOfWork.EmployeeRepository.Add(employee);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(employeeVM);
            }
        }
        #endregion

        #region Details
        public IActionResult Details(int? id, String viewName = "Details")
        {
            if (!id.HasValue)
                return BadRequest();
            var employee = _unitOfWork.EmployeeRepository.GetById(id.Value);
            _unitOfWork.Complete();

            if (employee is null)
                return NotFound();
            var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(employee);

            return View(viewName, mappedEmp);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int? id)
        {
            return Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute] int id, EmployeeViewModel employeeVm)
        {
            if (id != employeeVm.Id || employeeVm is null)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var employee = _mapper.Map<EmployeeViewModel, Employee>(employeeVm);
                    _unitOfWork.EmployeeRepository.Update(employee);
                    _unitOfWork.Complete();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(String.Empty, ex.Message);
                }
            }
            return View(employeeVm);

        }
        #endregion

        #region Delete
        public IActionResult Delete(int? id)
        {
            return Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([FromRoute] int id, EmployeeViewModel employeeVm)
        {
            if (id != employeeVm.Id || employeeVm is null)
                return BadRequest();

            try
            {
                var employee = _mapper.Map<EmployeeViewModel, Employee>(employeeVm);
                _unitOfWork.EmployeeRepository.Delete(employee);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(String.Empty, ex.Message);
            }

            return View(employeeVm);
        }
        #endregion
    }
}

First_MVC_APP/Controllers/UserController.cs
using AutoMapper;
using First_MVC_APP.DAL.Data.Models;
using First_MVC_APP.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace First_MVC_APP.PL.Controllers
{
    [Authorize]

    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager , IMapper mapper)
        {
            _userManager = userManager;
            _mapper = mapper;
        }

        #region Index

        public async Task<IActionResult> Index(string email)
        {
            var UsersVM = new List<UserViewModel>();
            if (string.IsNullOrEmpty(email))
            {
                var users = await _userManager.Users.ToListAsync();

                foreach (var user in users)
                {
                    var role = await _userManager.GetRolesAsync(user);

                    UsersVM.Add(new UserViewModel
                    {
                        Id = user.Id,
                        FName = user.FName,
                        LName = user.LName,
                        Email = user.Email,
                        PhoneNumber = user.PhoneNumber,
                        Roles = role,
                    });
                }

                return View(UsersVM);
            }
            else
            {
                var user = await _userManager.FindByEmailAsync(email);
                if (user is not null)
                {
                    UsersVM.Add(new UserViewModel()
                    {
                        Id = user.Id,
                        FName = user.FName,
                        LName = user.LName,
                        Email = user.Email,
                        PhoneNumber = user.PhoneNumber,
                        Roles = _userManager.GetRolesAsync(user).Result
                    });
                    return View(UsersVM);
                }
                return View(UsersVM);
            }

        }

        #endregion

        #region Details
        public async Task<IActionResult> Details(String id, String viewName = "Details")
        {
            if (String.IsNullOrEmpty(id))
                return BadRequest();
            var user = await _userManager.FindByIdAsync(id);

            if (user is null)
                return NotFound();

            var mappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);

            return View(viewName, mappedUser);
        }

        #endregion

        #region Edit

        public Task<IActionResult> Edit(String id)
        {
            return Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] String id, UserViewModel userVM)
        {
            if (id != userVM.Id || userVM is null)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(userVM.Id);
                    var updatedUser = _mapper.Map<UserViewModel, ApplicationUser>(userVM, user);
                    var result = await _userManager.UpdateAsync(updatedUser);
                    if (result.Succeeded)
                        return RedirectToAction(nameof(Index));

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(String.Empty, error.Description);
                     
                   
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(String.Empty, ex.Message);
                }
            }
            return View(userVM);

        }

        #endregion

        #region Delete
        public Task<IActionResult> Delete(String id)
        {
            return Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] String id, UserViewModel userVM)
        {
            if (id != userVM.Id || userVM is null)
                return BadRequest();

            try
            {
                var user = await _userManager.FindByIdAsync(userVM.Id);
                var mappedUser = _mapper.Map<UserViewModel, ApplicationUser>(userVM, user);
                var result = await _userManager.DeleteAsync(mappedUser);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(String.Empty, ex.Message);
            }

            return View(userVM);
        }
        #endregion


    }
}

First_MVC_APP/Views/Shared/_AuthLayout.cshtml
<!
<!DOCTYPE html>
<!-- Coding By CodingNepal - www.codingnepalweb.com -->
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Glassmorphism @ViewData["Title"] Form | CodingNepal</title>
    <link rel="stylesheet" href="~/css/AuthLayout.css" asp-append-version="true">
</head>
<body>
    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("ValidatoinScriptSection", required: false)
</body>
</html>

First_MVC_APP/Views/Shared/_BottonsPartial.cshtml
@model String

<td class="text-center">
<div class="btn-group" role="group">
    <a  asp-action="Details" asp-route-id="@Model"
       class="btn btn-sm btn-outline-warning">
        <i class="fas fa-eye"></i>
    </a>
    <a  asp-action="Edit" asp-route-id="@Model"
       class="btn btn-sm btn-outline-success">
        <i class="fas fa-edit"></i>
    </a>
    <a  asp-action="Delete" asp-route-id="@Model"
       class="btn btn-sm btn-outline-danger">
        <i class="fas fa-trash"></i>
    </a>
</div>
</td>

First_MVC_APP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - First_MVC_APP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand"  asp-controller="Home" asp-action="Index">First_MVC_APP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="SignOut">Sign out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-1 ">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - First_MVC_APP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidatoinScriptSection", required: false)
</body>
</html>